# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_ferramentas.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 249)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 211))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 381, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.btn_escolher_pasta = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_escolher_pasta.setObjectName("btn_escolher_pasta")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btn_escolher_pasta)
        self.btn_iniciar = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_iniciar.setObjectName("btn_iniciar")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_iniciar)
        self.msg_sucesso = QtWidgets.QLabel(self.tab)
        self.msg_sucesso.setGeometry(QtCore.QRect(130, 100, 373, 13))
        self.msg_sucesso.setObjectName("msg_sucesso")
        self.btn_abrir_relatorio = QtWidgets.QPushButton(self.tab)
        self.btn_abrir_relatorio.setGeometry(QtCore.QRect(130, 130, 161, 23))
        self.btn_abrir_relatorio.setObjectName("btn_abrir_relatorio")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btn_teste_escolher_pasta = QtWidgets.QPushButton(self.tab_2)
        self.btn_teste_escolher_pasta.setGeometry(QtCore.QRect(110, 30, 111, 23))
        self.btn_teste_escolher_pasta.setObjectName("btn_teste_escolher_pasta")
        self.btn_iniciar_teste = QtWidgets.QPushButton(self.tab_2)
        self.btn_iniciar_teste.setGeometry(QtCore.QRect(100, 90, 121, 23))
        self.btn_iniciar_teste.setObjectName("btn_iniciar_teste")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(50, 10, 331, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 261, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 341, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(60, 160, 281, 16))
        self.label_4.setObjectName("label_4")
        self.txt_escolha_uma_pasta = QtWidgets.QLabel(self.tab_2)
        self.txt_escolha_uma_pasta.setGeometry(QtCore.QRect(230, 30, 141, 16))
        self.txt_escolha_uma_pasta.setText("")
        self.txt_escolha_uma_pasta.setObjectName("txt_escolha_uma_pasta")
        self.tabWidget.addTab(self.tab_2, "")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButton.setGeometry(QtCore.QRect(250, 210, 185, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Organizador de pasta"))
        self.btn_escolher_pasta.setText(_translate("Dialog", "SELECIONAR PASTA"))
        self.btn_iniciar.setText(_translate("Dialog", "INICIAR"))
        self.msg_sucesso.setText(_translate("Dialog", "."))
        self.btn_abrir_relatorio.setText(_translate("Dialog", "ABRIR RELATÓRIO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Organizar arquivos"))
        self.btn_teste_escolher_pasta.setText(_translate("Dialog", "ESCOLHER PASTA"))
        self.btn_iniciar_teste.setText(_translate("Dialog", "INICIAR TESTE"))
        self.label.setText(_translate("Dialog", "1° ESCOLHA UMA PASTA, PARA FAZERMOS UM TESTE. "))
        self.label_2.setText(_translate("Dialog", "2° CLIQUE EM INICIAR TESTE"))
        self.label_3.setText(_translate("Dialog", "3°  IRA ABRIR UMA PASTA COM ARQUIVO TXT AVISANDO"))
        self.label_4.setText(_translate("Dialog", "SE O PROGRAMA ESTA PRONTO PARA SER UTILIZADO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "TESTAR ANTES DE USAR"))
        self.commandLinkButton.setText(_translate("Dialog", "@mwkbruno"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
